name: tec
description: this is techblog project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter         
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_slider_drawer: ^2.1.3
  flutter_svg: ^2.0.0 
  flutter_staggered_grid_view: ^0.7.0
  staggered_grid_view_flutter: ^0.0.4
  photo_manager: ^2.6.0
  dio: ^5.3.0
  shared_preferences: ^2.2.0
 
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  flutter_gen_runner:



flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/stories/
    - assets/images/
    - assets/icons/menu/
    - assets/icons/nav_bottom/
    - assets/icons/userprofilescreen/

  fonts:
    - family: dana
      fonts:
        - asset: assets/fonts/DANA-BOLD.ttf
          weight: 700
        - asset: assets/fonts/DANA-REGULAR.ttf
          weight: 300    
    - family: semibold
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf